/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as cpammSol from "./CPAMM.sol";
export { ERC20__factory } from "./ERC20__factory";
export { ERC20_A__factory } from "./ERC20_A__factory";
export { IERC20__factory } from "./IERC20__factory";
