/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cpammSol from "./CPAMM.sol";
export type { cpammSol };
export type { ERC20 } from "./ERC20";
export type { ERC20_A } from "./ERC20_A";
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export type { CPAMM } from "./CPAMM.sol/CPAMM";
export { CPAMM__factory } from "./factories/CPAMM.sol/CPAMM__factory";
export type { IERC20 } from "./CPAMM.sol/IERC20";
export { IERC20__factory } from "./factories/CPAMM.sol/IERC20__factory";
export { ERC20_A__factory } from "./factories/ERC20_A__factory";
export { ERC20__factory } from "./factories/ERC20__factory";
